name: Scheduled Airtable Update and Netlify Deploy

on:
  schedule:
    - cron: '25 9 14 3 *' # Runs at 1:25 AM PST (9:25 AM UTC)

jobs:
  update_airtable_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Update Airtable Records
        env:
          AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
          AIRTABLE_BASE_ID: ${{ secrets.AIRTABLE_BASE_ID }}
        run: |
          curl -X PATCH "https://api.airtable.com/v0/$AIRTABLE_BASE_ID/YOUR_TABLE_NAME" \
            -H "Authorization: Bearer $AIRTABLE_API_KEY" \
            -H "Content-Type: application/json" \
            --data '{
              "records": [
                {"id": "rec6Bo638LqnaCtx3", "fields": {"Lock Brackets": "True"}},
                {"id": "recvLoL2payK7901n", "fields": {"Lock Brackets": "True"}},
                {"id": "recq7aE672G7eJUzx", "fields": {"Lock Brackets": "True"}},
                {"id": "reciulRlhQoChDpwS", "fields": {"Lock Brackets": "True"}}
              ]
            }'

      - name: Trigger Netlify Deploy
        env:
          NETLIFY_BUILD_HOOK: ${{ secrets.NETLIFY_BUILD_HOOK }}
        run: |
          curl -X POST -d '{}' "$NETLIFY_BUILD_HOOK"
